expenses/accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("accoounts/create/", views.create_account, name="create_account"),
]

expenses/expenses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url="receipts/", permanent=False)),
    path("categories/create/", views.create_expense_category, name="create_category"),
]

expenses/receipts/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from . import views

urlpatterns = [
    path("", views.receipt_list_view, name="home"),
    path("", views.receipt_list_view, name="receipt_list"),
    path("create/", views.create_receipt, name="create_receipt"),
    path("categories/", views.category_list, name="category_list"),
    path("accounts/", views.account_list, name="account_list"),
]

expenses/accounts/models.py
from django.db import models
from .models import Receipt

# Create your models here.
class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=50)

expenses/receipts/models.py
from django.db import models
from django.contrib.auth.models import User
from .models import Receipt

# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(User, related_name="categories", on_delete=models.CASCADE)

class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(User, related_name="accounts", on_delete=models.CASCADE)

class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(User, related_name="receipts", on_delete=models.CASCADE)
    category = models.ForeignKey(ExpenseCategory, related_name="recipts", on_delete=models.CASCADE)
    account = models.ForeignKey(Account, related_name="receipts", on_delete=models.CASCADE, null=True)

expenses/accounts/forms.py
from django import forms
from .models import Account

class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)

class SignUpForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput)
    password_confirmation = forms.CharField(max_length=150, widget=forms.PasswordInput)

class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ["name", "number"]

expenses/expenses/forms.py
from django import forms
from .models import ExpenseCategory

class ExpenseCategoryForm(forms.ModelForm):
    class Meta:
        model = ExpenseCategory
        fields = ['name']

expenses/receipts/forms.py
from django import forms
from django import Receipt

class ReceiptForm(forms.ModelForm):
    class Meta:
        model = Receipt
        fields = ["vendor", "total", "tax", "date", "category", "account"]

expenses/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.urls import reverse
from .forms import LoginForm, SignUpForm, AccountForm

# Create your views here.
def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(user=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("home")

    else:
        form = LoginForm()
    return render(request, "accounts/login.html", {"form": form})

def logout_view(request):
    logout(request)
    return redirect(reverse("login"))

def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password_confirmation = form.cleaned_data["password_confirmation"]

            if password == password.confirmation:
                user = User.objects.create_user(username=username, password=password)
                login(request, user)
                return redirect("receipt_list")
            else:
                error = "The passwords do not match"
                return render(request, "registration/signup.html", {"form": form, "error": error})
        else:
            form = SignUpForm()
            return render(request, "registration/signup.html", {"form": form})

def create_account(request):
    if request.method == "POST":
        form = AccountForm(request.POST)
        if form.is_valid():
            account = form.save(commit=False)
            account.owner = request.user
            account.save()
            return redirect("account_list")

    else:
        form = AccountForm()
    return render(request, "create_account.html", {"form": form})

expenses/expenses/views.py
from django.shortcuts import render, redirect
from .forms import ExpenseCategoryForm

def create_expense_category(request):
    if request.method == 'POST':
        form = ExpenseCategoryForm(request.POST)
        if form.is_valid():
            expense_category = form.save(commit=False)
            expense_category.owner = request.user  # Set the owner to the current user
            expense_category.save()
            return redirect('category_list')  # Redirect to the list of categories
    else:
        form = ExpenseCategoryForm()
    return render(request, 'create_category.html', {'form': form})

expenses/receipts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Receipt, ExpenseCategory, Account
from .forms import ReceiptForm

# Create your views here.
def receipt_list_view(request):
    receipts = Receipt.objects.filter(purchaser=request.user)
    context = {"receipts": receipts}
    return render(request, "recipts/receipts/receipt_list.html", context)

def create_receipt(request):
    if request.method == "POST":
        form = ReceiptForm(request.POST)
        if form.is_valid():
            receipt = form.save(commit=False)
            receipt.purchaser = request.user
            receipt.sxave()
            return redirect("home")
    else:
        form = ReceiptForm()

    return render(request, "receipts/create_receipt.html", {"form": form})

def category_list(request):
    expense_categories = ExpenseCategory.objects.filter(user_property=request.user)
    context = {
        "expense_categories": expense_categories
    }
    return render(request, "receipts/category_list.html", context)

def account_list(request):
    accounts = Account.objects.filter(user_property=request.user)
    context = {
        "accounts": accounts
    }
    return render(request, "receipts/account_list.html", context)

expenses/accounts/templates/create_account.html
<!DOCTYPE html>
<html>
    <head>
        <title>Create Account</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Create Account</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

expenses/accounts/templates/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>Login</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Login</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Login</button>
                </form>
            </div>
        </main>
    </body>
</html>

expenses/accounts/templates/signup.html
<!DOCTYPE html>
<html>
    <head>
        <title>Signup</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Signup</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit">Signup</button>
                </form>
                {% if error %}<p>{{ error }}</p>{% endif %}
            </div>
        </main>
    </body>
</html>

expenses/expenses/templates/create_category.html
<!DOCTYPE html>
<html>
    <head>
        <title>Create Expense Category</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Create Category</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

expenses/receipts/templates/account_list.html
<!DOCTYPE html>
<html>
    <head>
        <title>Accounts List</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li>
                        <a href="{% url 'category_list' %}">Expense Categories</a>
                    </li>
                    <li>
                        <a href="{% url 'create_category' %}">Create Expense Category</a>
                    </li>
                    <li>
                        <a href="{% url 'account_list' %}">Accounts</a>
                    </li>
                    <li>
                        <a href="{% url 'create_account' %}">Create Account</a>
                    </li>
                </ul>
            </nav>
        </header>
        <main>
            <h1>Accounts</h1>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number</th>
                        <th>Number of receipts</th>
                    </tr>
                </thead>
                <tbody>
                    {% for account in accounts %}
                        <tr>
                            <td>{{ account.name }}</td>
                            <td>{{ account.number }}</td>
                            <td>{{ account.receipt_set.count }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </main>
    </body>
</html>

expenses/receipts/templates/category_list.html
<!DOCTYPE html>
<html>
    <head>
        <title>Expense Categories List</title>
    </head>
    <body>
        <main>
            <h1>Expense Categories</h1>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of receipts</th>
                    </tr>
                </thead>
                <tbody>
                    {% for category in expense_categories %}
                        <tr>
                            <td>{{ category.name }}</td>
                            <td>{{ category.receipt_set.count }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </main>
    </body>
</html>

expenses/receipts/templates/create_receipt.html
<!DOCTYPE html>
<html>
    <head>
        <title>Create Receipt</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Create Receipt</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

expenses/receipts/templates/receipt_list.html
<!DOCTYPE html>
<html>
    <head>
        <title>My Receipts</title>
    </head>
    <body>
        <main>
            <h1>My Receipts</h1>
            <table>
                <tr>
                    <th>Vendor</th>
                    <th>Total</th>
                    <th>Tax</th>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Account</th>
                </tr>
                {% for receipt in receipts %}
                    <tr>
                        <td>{{ receipt.vendor }}</td>
                        <td>{{ receipt.total }}</td>
                        <td>{{ receipt.tax }}</td>
                        <td>{{ receipt.date|date:"m/d/y" }}</td>
                        <td>{{ receipt.category.name }}</td>
                        <td>{{ receipt.account.name }}</td>
                    </tr>
                {% endfor %}
            </table>
        </main>
    </body>
</html>